import os
from dotenv import load_dotenv
load_dotenv()
class AuthenConfig:
    BASE_URL=os.getenv("BASE_URL")
    LOGIN_ENDPOINT=os.getenv("LOGIN_ENDPOINT")
    EMPTYCART_ENDPOINT=os.getenv("EMPTYCART_ENDPOINT")
    CART_ENDPOINT=os.getenv("CART_ENDPOINT")
    ADD_ITEM_ENDPOINT=os.getenv("ADD_ITEM_ENDPOINT")
    ADD_FEE_ENDPOINT=os.getenv("ADD_FEE_ENDPOINT")
    GETCART_ENPOINT=os.getenv("GETCART_ENPOINT")
    GET_CART_ITEM_ENDPOINT=os.getenv("GET_CART_ITEM_ENDPOINT")
    ESTIMATESHIPPINGMETHOD_ENPOINT=os.getenv("ESTIMATESHIPPINGMETHOD_ENPOINT")
    SAVESHIPPINGINFOMATION_ENDPOINT=os.getenv("SAVESHIPPINGINFOMATION_ENDPOINT")
    N_USERNAME=os.getenv("N_USERNAME")
    PASSWORD=os.getenv("PASSWORD")